using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReportesWeb1_2.ModelsReportes
{
    public class TurnoCarrilesModel
    {
        [Display(Name = "Delegación")]
        public string IdDelegacion { get; set; }

        public List<SelectListItem> ListDelegaciones { get; set; }

        [Display(Name = "Plazas de Cobro")]
        public string IdPlaza { get; set; }

        public List<SelectListItem> ListPlazas { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido.")]
        [Display(Name = "Turnos")]
        public string IdTurno { get; set; }

        public List<SelectListItem> ListTurnos { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido.")]
        [Display(Name = "Encargado de Turno")]
        public string IdEncargadoTurno { get; set; }

        public List<SelectListItem> ListEncargadosTurno { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido.")]
        [Display(Name = "Administrador")]
        public string IdAdministrador { get; set; }

        public List<SelectListItem> ListAdministradores { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido.")]
        [Display(Name = "Fecha")]
        public DateTime Fecha { get; set; }

        [Required(ErrorMessage = "El campo {0} es requerido.")]
        [Display(Name = "Observaciones")]
        public string Observaciones { get; set; }

        [NotMapped]
        public PreTCViewModel PreTCViewModel { get; set; }

        [NotMapped]
        public ComTCViewModel ComTCViewModel { get; set; }
    }

    public class PreTCViewModel
    {
        public string Par3 { get; set; }
        public string Par7 { get; set; }
        public string Par4 { get; set; }
        public string Par1 { get; set; }
        public string Par69 { get; set; }
        public string Par74 { get; set; }
        public string Par79 { get; set; }
        public string Par89 { get; set; }
        public string Par98 { get; set; }
        public string Par5 { get; set; }
        public string Par99 { get; set; }
        public string Par9 { get; set; }
        public string Par94 { get; set; }
        public string Par63 { get; set; }
        public string Par65 { get; set; }
        public string Par67 { get; set; }
        //par11, par12, par13, par14, par15, par16, par17, par18, par19, par20, par21, par22, par23, par24, par25, par26, par27, par28, par29,
        public string Par11 { get; set; }
        public string Par12 { get; set; }
        public string Par13 { get; set; }
        public string Par14 { get; set; }
        public string Par15 { get; set; }
        public string Par16 { get; set; }
        public string Par17 { get; set; }
        public string Par18 { get; set; }
        public string Par19 { get; set; }
        public string Par20 { get; set; }
        public string Par21 { get; set; }
        public string Par22 { get; set; }
        public string Par23 { get; set; }
        public string Par24 { get; set; }
        public string Par25 { get; set; }
        public string Par26 { get; set; }
        public string Par27 { get; set; }
        public string Par28 { get; set; }
        public string Par29 { get; set; }
        // par30, par3,, par32, par33, par34, par35, par36, par37, par38, par39, par40, par41, par42, par43, par140, par141, par142, par143, par44, par45, par46, 
        public string Par30 { get; set; }
        public string Par31 { get; set; }
        public string Par32 { get; set; }
        public string Par33 { get; set; }
        public string Par34 { get; set; }
        public string Par35 { get; set; }
        public string Par36 { get; set; }
        public string Par37 { get; set; }
        public string Par38 { get; set; }
        public string Par39 { get; set; }
        public string Par40 { get; set; }
        public string Par41 { get; set; }
        public string Par42 { get; set; }
        public string Par43 { get; set; }
        public string Par140 { get; set; }
        public string Par141 { get; set; }
        public string Par142 { get; set; }
        public string Par143 { get; set; }
        public string Par44 { get; set; }
        public string Par45 { get; set; }
        public string Par46 { get; set; }
        //par47, par48, par49, par50, par51, par52, par53, par54, par55, par56, par57, par58, par59, par60, par61, par62, par72, par73, par87, par88
        public string Par47 { get; set; }
        public string Par48 { get; set; }
        public string Par49 { get; set; }
        public string Par50 { get; set; }
        public string Par51 { get; set; }
        public string Par52 { get; set; }
        public string Par53 { get; set; }
        public string Par54 { get; set; }
        public string Par55 { get; set; }
        public string Par56 { get; set; }
        public string Par57 { get; set; }
        public string Par58 { get; set; }
        public string Par59 { get; set; }
        public string Par60 { get; set; }
        public string Par61 { get; set; }
        public string Par62 { get; set; }
        public string Par72 { get; set; }
        public string Par73 { get; set; }
        public string Par87 { get; set; }
        public string Par88 { get; set; }
        public string Par96 { get; set; }

        public string Parelu1 { get; set; }
        public string Parelu2 { get; set; }
        public string Parelu3 { get; set; }
        public string Parelu4 { get; set; }
    }

    public class ComTCViewModel
    {
        //public List<SelectListItem> Par1 { get; set; }
        public string Par2 { get; set; }
        public string Par3 { get; set; }
        public string Par4 { get; set; }
        //public string Par5 { get; set; }
        //public string Par6 { get; set; }
        public string Par7 { get; set; }
        //public string Par8 { get; set; }
        //public string Par9 { get; set; }
        //public string Par10 { get; set; }
        //public string Par11 { get; set; }
        public string Par12 { get; set; }
        public string Par13 { get; set; }
        public string Par14 { get; set; }
        public string Par15 { get; set; }
        public string Par16 { get; set; }
        public string Par17 { get; set; }
        public string Par18 { get; set; }
        public string Par19 { get; set; }
        public string Par20 { get; set; }
        public string Par21 { get; set; }
        public string Par22 { get; set; }
        public string Par23 { get; set; }
        public string Par24 { get; set; }
        public string Par25 { get; set; }
        public string Par26 { get; set; }
        public string Par27 { get; set; }
        public string Par28 { get; set; }
        public string Par29 { get; set; }
        public string Par30 { get; set; }
        public string Par31 { get; set; }
        public string Par32 { get; set; }
        public string Par33 { get; set; }
        public string Par34 { get; set; }
        public string Par35 { get; set; }
        public string Par36 { get; set; }
        public string Par37 { get; set; }
        public string Par38 { get; set; }
        public string Par39 { get; set; }
        public string Par40 { get; set; }
        public string Par41 { get; set; }
        public string Par42 { get; set; }
        public string Par43 { get; set; }
        public string Par44 { get; set; }
        public string Par45 { get; set; }
        public string Par46 { get; set; }
        public string Par47 { get; set; }
        public string Par48 { get; set; }
        public string Par49 { get; set; }
        public string Par50 { get; set; }
        public string Par51 { get; set; }
        public string Par52 { get; set; }
        public string Par53 { get; set; }
        public string Par54 { get; set; }
        public string Par55 { get; set; }
        public string Par56 { get; set; }
        public string Par57 { get; set; }
        public string Par58 { get; set; }
        public string Par59 { get; set; }
        public string Par60 { get; set; }
        public string Par61 { get; set; }
        public string Par62 { get; set; }
        public string Par63 { get; set; }
        public string Par64 { get; set; }
        public string Par65 { get; set; }
        public string Par66 { get; set; }
        public string Par67 { get; set; }
        public string Par68 { get; set; }
        public string Par69 { get; set; }
        public string Par70 { get; set; }
        public string Par71 { get; set; }
        public string Par72 { get; set; }
        public string Par73 { get; set; }
        public string Par74 { get; set; }
        public string Par75 { get; set; }
        public string Par76 { get; set; }
        public string Par77 { get; set; }
        public string Par78 { get; set; }
        public string Par79 { get; set; }
        public string Par80 { get; set; }
        public string Par81 { get; set; }
        public string Par82 { get; set; }
        public string Par83 { get; set; }
        public string Par84 { get; set; }
        public string Par85 { get; set; }
        public string Par86 { get; set; }
        public string Par87 { get; set; }
        public string Par88 { get; set; }
        public string Par89 { get; set; }
        public string Par90 { get; set; }
        public string Par91 { get; set; }
        public string Par92 { get; set; }
        public string Par93 { get; set; }
        public string Par94 { get; set; }
        public string Par95 { get; set; }
        public string Par96 { get; set; }
        public string Par97 { get; set; }
        public string Par98 { get; set; }
        public string Par99 { get; set; }
        public string Par100 { get; set; }
        public string Par101 { get; set; }
        public string Par102 { get; set; }
        public string Par103 { get; set; }
        public string Par104 { get; set; }
        public string Par105 { get; set; }
        public string Par106 { get; set; }
        public string Par107 { get; set; }
        public string Par108 { get; set; }
        public string Par109 { get; set; }
        public string Par110 { get; set; }
        public string Par111 { get; set; }
        public string Par112 { get; set; }
        public string Par113 { get; set; }
        public string Par114 { get; set; }
        public string Par115 { get; set; }
        public string Par116 { get; set; }
        public string Par117 { get; set; }
        public string Par118 { get; set; }
        public string Par119 { get; set; }
        public string Par120 { get; set; }
        public string Par121 { get; set; }
        public string Par122 { get; set; }
        public string Par123 { get; set; }
        public string Par124 { get; set; }
        public string Par125 { get; set; }
        public string Par126 { get; set; }
        public string Par127 { get; set; }
        public string Par128 { get; set; }
        public string Par129 { get; set; }
        public string Par130 { get; set; }
        public string Par131 { get; set; }
        public string Par132 { get; set; }
        public string Par133 { get; set; }
        public string Par134 { get; set; }
        public string Par135 { get; set; }
        public string Par136 { get; set; }
        public string Par137 { get; set; }
        public string Par138 { get; set; }
        public string Par139 { get; set; }
        public string Par140 { get; set; }
        public string Par141 { get; set; }
        public string Par142 { get; set; }
        public string Par143 { get; set; }
        public string Par144 { get; set; }
        public string Par145 { get; set; }
        public string Par146 { get; set; }
        public string Par147 { get; set; }
        public string Par148 { get; set; }
        public string Par149 { get; set; }
        public string Par150 { get; set; }
        public string Par151 { get; set; }
        public string Par152 { get; set; }
        public string Par153 { get; set; }
        public string Par154 { get; set; }
        public string Par155 { get; set; }
        public string Par156 { get; set; }
        public string Par157 { get; set; }
        public string Par158 { get; set; }
        public string Par159 { get; set; }
        public string Par160 { get; set; }
        public string Par161 { get; set; }
        public string Par162 { get; set; }
        public string Par163 { get; set; }
        public string Par164 { get; set; }
        public string Par165 { get; set; }
        public string Par166 { get; set; }
        public string Par167 { get; set; }
        public string Par168 { get; set; }
        public string Par169 { get; set; }
        public string Par170 { get; set; }
        public string Par171 { get; set; }
        public string Par172 { get; set; }
        public string Par173 { get; set; }
        public string Par174 { get; set; }
        public string Par175 { get; set; }
        public string Par176 { get; set; }
        public string Par177 { get; set; }
        public string Par178 { get; set; }
        public string Par179 { get; set; }
        public string Par180 { get; set; }
        public string Par181 { get; set; }
        public string Par182 { get; set; }
        public string Par183 { get; set; }
        public string Par184 { get; set; }
        public string Par185 { get; set; }
        public string Par186 { get; set; }
        public string Par187 { get; set; }
        public string Par188 { get; set; }
        public string Par189 { get; set; }
        public string Par190 { get; set; }
        public string Par191 { get; set; }
        public string Par192 { get; set; }
        public string Par193 { get; set; }
        public string Par194 { get; set; }
        public string Par195 { get; set; }
        public string Par196 { get; set; }
        public string Par197 { get; set; }
        public string Par198 { get; set; }
        public string Par199 { get; set; }
        public string Par200 { get; set; }
        public string Par201 { get; set; }
        public string Par202 { get; set; }
        public string Par203 { get; set; }
        public string Par204 { get; set; }
        public string Par205 { get; set; }
        public string Par206 { get; set; }
        public string Par207 { get; set; }
        public string Par208 { get; set; }
        public string Par209 { get; set; }
        public string Par210 { get; set; }
        public string Par211 { get; set; }
        public string Par212 { get; set; }
        public string Par213 { get; set; }
        public string Par214 { get; set; }
        public string Par215 { get; set; }
        public string Par216 { get; set; }
        public string Par217 { get; set; }
        public string Par218 { get; set; }
        public string Par219 { get; set; }
        public string Par220 { get; set; }
        public string Par221 { get; set; }
        public string Par222 { get; set; }
        public string Par223 { get; set; }
        public string Par224 { get; set; }
        public string Par225 { get; set; }
        public string Par226 { get; set; }
        public string Par227 { get; set; }
        public string Par228 { get; set; }
        public string Par229 { get; set; }
        public string Par230 { get; set; }
        public string Par231 { get; set; }
        public string Par232 { get; set; }
        public string Par233 { get; set; }
        public string Par234 { get; set; }
        public string Par235 { get; set; }
        public string Par236 { get; set; }
        public string Par237 { get; set; }
        public string Par238 { get; set; }
        public string Par239 { get; set; }
        public string Par240 { get; set; }
        public string Par241 { get; set; }
        public string Par242 { get; set; }
        public string Par243 { get; set; }
        public string Par244 { get; set; }
        public string Par245 { get; set; }
        public string Par246 { get; set; }
        public string Par247 { get; set; }
        public string Par248 { get; set; }
        public string Par249 { get; set; }
        public string Par250 { get; set; }
        public string Par251 { get; set; }
        public string Par252 { get; set; }
        public string Par253 { get; set; }
        public string Par254 { get; set; }
        public string Par255 { get; set; }
        public string Par256 { get; set; }
        public string Par257 { get; set; }
        public string Par258 { get; set; }
        public string Par259 { get; set; }
        public string Par260 { get; set; }
        public string Par261 { get; set; }
        public string Par262 { get; set; }
        public string Par263 { get; set; }
        public string Par264 { get; set; }
        public string Par265 { get; set; }
        public string Par266 { get; set; }
        public string Par267 { get; set; }
        public string Par268 { get; set; }
        public string Par269 { get; set; }
        public string Par270 { get; set; }
        public string Par271 { get; set; }
        public string Par272 { get; set; }
        public string Par273 { get; set; }
        public string Par274 { get; set; }
        public string Par275 { get; set; }
        public string Par276 { get; set; }
        public string Par277 { get; set; }
        public string Par278 { get; set; }
        public string Par279 { get; set; }
        public string Par280 { get; set; }
        public string Par281 { get; set; }
        public string Par282 { get; set; }
        public string Par283 { get; set; }
        public string Par284 { get; set; }
        public string Par285 { get; set; }
        public string Par286 { get; set; }
        public string Par287 { get; set; }
        public string Par288 { get; set; }
        public string Par289 { get; set; }
        public string Par290 { get; set; }
        public string Par291 { get; set; }
        public string Par292 { get; set; }
        public string Par293 { get; set; }
        public string Par294 { get; set; }
        public string Par295 { get; set; }
        public string Par296 { get; set; }
        public string Par297 { get; set; }
        public string Par298 { get; set; }
        public string Par299 { get; set; }
        public string Par300 { get; set; }
        public string Par301 { get; set; }
        public string Par302 { get; set; }
        public string Par303 { get; set; }
        public string Par304 { get; set; }
        public string Par305 { get; set; }
        public string Par306 { get; set; }
        public string Par307 { get; set; }
        public string Par308 { get; set; }
        public string Par309 { get; set; }
        public string Par310 { get; set; }
        public string Par311 { get; set; }
        public string Par312 { get; set; }
        public string Par313 { get; set; }
        public string Par314 { get; set; }
        public string Par315 { get; set; }
        public string Par316 { get; set; }
        public string Par317 { get; set; }
        public string Par318 { get; set; }
        public string Par319 { get; set; }
        public string Par320 { get; set; }
        public string Par321 { get; set; }
        public string Par322 { get; set; }
        public string Par323 { get; set; }
        public string Par324 { get; set; }
        public string Par325 { get; set; }
        public string Par326 { get; set; }
        public string Par327 { get; set; }
        public string Par328 { get; set; }
        public string Par329 { get; set; }
        public string Par330 { get; set; }
        public string Par331 { get; set; }
        public string Par332 { get; set; }
        public string Par333 { get; set; }
        public string Par334 { get; set; }
        public string Par335 { get; set; }
        public string Par336 { get; set; }
        public string Par337 { get; set; }
        public string Par338 { get; set; }
        public string Par339 { get; set; }
        public string Par340 { get; set; }
        public string Par341 { get; set; }
        public string Par342 { get; set; }
        public string Par343 { get; set; }
        public string Par344 { get; set; }
        public string Par345 { get; set; }
        public string Par346 { get; set; }
        public string Par347 { get; set; }
        public string Par348 { get; set; }
        public string Par349 { get; set; }
        public string Par350 { get; set; }
        public string Par351 { get; set; }
        public string Par352 { get; set; }
        public string Par353 { get; set; }
        public string Par354 { get; set; }
        public string Par355 { get; set; }
        public string Par356 { get; set; }
        public string Par357 { get; set; }
        public string Par358 { get; set; }
        public string Par359 { get; set; }
        public string Par360 { get; set; }
        public string Par361 { get; set; }
        public string Par362 { get; set; }
        public string Par363 { get; set; }
        public string Par364 { get; set; }
        public string Par365 { get; set; }
        public string Par366 { get; set; }
        public string Par367 { get; set; }
        public string Par368 { get; set; }
        public string Par369 { get; set; }
        public string Par370 { get; set; }
        public string Par371 { get; set; }
        public string Par372 { get; set; }
        public string Par373 { get; set; }
        public string Par374 { get; set; }
        public string Par375 { get; set; }
        public string Par376 { get; set; }
        public string Par377 { get; set; }
        public string Par378 { get; set; }
        public string Par379 { get; set; }
        public string Par380 { get; set; }
        public string Par381 { get; set; }
        public string Par382 { get; set; }
        public string Par383 { get; set; }
        public string Par384 { get; set; }
        public string Par385 { get; set; }
        public string Par386 { get; set; }
        public string Par387 { get; set; }
        public string Par388 { get; set; }
        public string Par389 { get; set; }
        public string Par390 { get; set; }
        public string Par391 { get; set; }
        public string Par392 { get; set; }
        public string Par393 { get; set; }
        public string Par394 { get; set; }
        public string Par395 { get; set; }
        public string Par396 { get; set; }
        public string Par397 { get; set; }
        public string Par398 { get; set; }
        public string Par399 { get; set; }
        public string Par400 { get; set; }
        public string Par401 { get; set; }
        public string Par402 { get; set; }
        public string Par403 { get; set; }
        public string Par404 { get; set; }
        public string Par405 { get; set; }
        public string Par406 { get; set; }
        public string Par407 { get; set; }
        public string Par408 { get; set; }
        public string Par409 { get; set; }
        public string Par410 { get; set; }
        public string Par411 { get; set; }
        public string Par412 { get; set; }
        public string Par413 { get; set; }
        public string Par414 { get; set; }
        public string Par415 { get; set; }
        public string Par416 { get; set; }
        public string Par417 { get; set; }
        public string Par418 { get; set; }
        public string Par419 { get; set; }
        public string Par420 { get; set; }
        public string Par421 { get; set; }
        public string Par422 { get; set; }
        public string Par423 { get; set; }
        public string Par424 { get; set; }
        public string Par425 { get; set; }
        public string Par426 { get; set; }
        public string Par427 { get; set; }
        public string Par428 { get; set; }
        public string Par429 { get; set; }
        public string Par430 { get; set; }
        public string Par431 { get; set; }
        public string Par432 { get; set; }
        public string Par433 { get; set; }
        public string Par434 { get; set; }
        public string Par435 { get; set; }
        public string Par436 { get; set; }
        public string Par437 { get; set; }
        public string Par438 { get; set; }
        public string Par439 { get; set; }
        public string Par440 { get; set; }
        public string Par441 { get; set; }
        public string Par442 { get; set; }
        public string Par443 { get; set; }
        public string Par444 { get; set; }
        public string Par445 { get; set; }
        public string Par446 { get; set; }
        public string Par447 { get; set; }
        public string Par448 { get; set; }
        public string Par449 { get; set; }
        public string Par450 { get; set; }
        public string Par451 { get; set; }
        public string Par452 { get; set; }
        public string Par453 { get; set; }
        public string Par454 { get; set; }
        public string Par455 { get; set; }
        public string Par456 { get; set; }
        public string Par457 { get; set; }
        public string Par458 { get; set; }
        public string Par459 { get; set; }
        public string Par460 { get; set; }
        public string Par461 { get; set; }
        public string Par462 { get; set; }
        public string Par463 { get; set; }
        public string Par464 { get; set; }
        public string Par465 { get; set; }
        public string Par466 { get; set; }
        public string Par467 { get; set; }
        public string Par468 { get; set; }
        public string Par469 { get; set; }
        public string Par470 { get; set; }
        public string Par471 { get; set; }
        public string Par472 { get; set; }
        public string Par473 { get; set; }
        public string Par474 { get; set; }
        public string Par475 { get; set; }
        public string Par476 { get; set; }
        public string Par477 { get; set; }
        public string Par478 { get; set; }
        public string Par479 { get; set; }
        public string Par480 { get; set; }
        public string Par481 { get; set; }
        public string Par482 { get; set; }
        public string Par483 { get; set; }
        public string Par484 { get; set; }
        public string Par485 { get; set; }
        public string Par486 { get; set; }
        public string Par487 { get; set; }
        public string Par488 { get; set; }
        public string Par489 { get; set; }
        public string Par490 { get; set; }
        public string Par491 { get; set; }
        public string Par492 { get; set; }
        public string Par493 { get; set; }
        public string Par494 { get; set; }
        public string Par495 { get; set; }
        public string Par496 { get; set; }
        public string Par497 { get; set; }
        public string Par498 { get; set; }
        public string Par499 { get; set; }
        public string Par500 { get; set; }
        public string Par501 { get; set; }
        public string Par502 { get; set; }
        public string Par503 { get; set; }
        public string Par504 { get; set; }
        public string Par505 { get; set; }
        public string Par506 { get; set; }
        public string Par507 { get; set; }
        public string Par508 { get; set; }
        public string Par509 { get; set; }
        public string Par510 { get; set; }
        public string Par511 { get; set; }
        public string Par512 { get; set; }
        public string Par513 { get; set; }
        public string Par514 { get; set; }
        public string Par515 { get; set; }
        public string Par516 { get; set; }
        public string Par517 { get; set; }
        public string Par518 { get; set; }
        public string Par519 { get; set; }
        public string Par520 { get; set; }
        public string Par521 { get; set; }
        public string Par522 { get; set; }
        public string Par523 { get; set; }

        //Gerardo
        public string Par524 { get; set; }
        public string Par525 { get; set; }
        public string Par526 { get; set; }
        public string Par527 { get; set; }
        public string Par528 { get; set; }
        public string Par529 { get; set; }
        public string Par530 { get; set; }
        public string Par531 { get; set; }
        public string Par532 { get; set; }
        public string Par533 { get; set; }
        public string Par534 { get; set; }
        public string Par535 { get; set; }
        public string Par536 { get; set; }
        public string Par537 { get; set; }
        public string Par538 { get; set; }
        public string Par539 { get; set; }

        public string Par540 { get; set; }
        public string Par541 { get; set; }
        public string Par542 { get; set; }
        public string Par543 { get; set; }
        public string Par544 { get; set; }
        public string Par545 { get; set; }
        public string Par546 { get; set; }
        public string Par547 { get; set; }
        public string Par548 { get; set; }
        public string Par549 { get; set; }
        public string Par550 { get; set; }
        public string Par551 { get; set; }
        public string Par552 { get; set; }
        public string Par553 { get; set; }
        public string Par554 { get; set; }
        public string Par555 { get; set; }
        public string Par556 { get; set; }
        public string Par557 { get; set; }
        public string Par558 { get; set; }
        public string Par559 { get; set; }
        public string Par560 { get; set; }
        public string Par561 { get; set; }
        public string Par562 { get; set; }
        public string Par563 { get; set; }
        public string Par564 { get; set; }
        public string Par565 { get; set; }
        public string Par566 { get; set; }
        public string Par567 { get; set; }
        public string Par568 { get; set; }
        public string Par569 { get; set; }
        public string Par570 { get; set; }
        public string Par571 { get; set; }
        public string Par572 { get; set; }
        public string Par573 { get; set; }
        public string Par574 { get; set; }
        public string Par575 { get; set; }
        public string Par576 { get; set; }
        public string Par577 { get; set; }
        public string Par578 { get; set; }
        public string Par579 { get; set; }
        public string Par580 { get; set; }
        public string Par581 { get; set; }
        public string Par582 { get; set; }
        public string Par583 { get; set; }
        public string Par584 { get; set; }
        public string Par585 { get; set; }
        public string Par586 { get; set; }
        public string Par587 { get; set; }
        public string Par588 { get; set; }
        public string Par589 { get; set; }
        public string Par590 { get; set; }
        public string Par591 { get; set; }
        public string Par592 { get; set; }
        public string Par593 { get; set; }
        public string Par594 { get; set; }
        public string Par595 { get; set; }
        public string Par596 { get; set; }
        public string Par597 { get; set; }
        public string Par598 { get; set; }
        public string Par599 { get; set; }
        public string Par600 { get; set; }
        public string Par601 { get; set; }
        public string Par602 { get; set; }
        public string Par603 { get; set; }
        public string Par604 { get; set; }
        public string Par605 { get; set; }
        public string Par606 { get; set; }
        public string Par607 { get; set; }
        public string Par608 { get; set; }
        public string Par609 { get; set; }
        public string Par610 { get; set; }
        public string Par611 { get; set; }
        public string Par612 { get; set; }
        public string Par613 { get; set; }
        public string Par614 { get; set; }
        public string Par615 { get; set; }
        public string Par616 { get; set; }
        public string Par617 { get; set; }
        public string Par618 { get; set; }
    }
}